version: "3"
services:
  postgres:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_USER: "covee-saas"
      POSTGRES_PASSWORD: "password"
    ports:
      - "127.0.0.1:5432:5432"
  # elasticsearch:
  #   image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.0"
  #   ports: 
  #     - "127.0.0.1:9200:9200"
  #     - "127.0.0.1:9300:9300"
  #   environment:
  #     - discovery.type=single-node
  #   restart: "on-failure"
  # kibana:
  #   image: "docker.elastic.co/kibana/kibana:7.5.0"
  #   ports: 
  #     - "127.0.0.1:5601:5601"
  #   links:
  #     - elasticsearch
  #   restart: "on-failure"
  # apm:
  #   image: "docker.elastic.co/apm/apm-server:7.5.0"
  #   ports: 
  #     - "127.0.0.1:8200:8200"
  #   restart: "on-failure"
  azure-blob-storage:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "127.0.0.1:10000:10000"   
  mailhog:
    image: "mailhog/mailhog"
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
  amqp:
    image: "rabbitmq:3-management-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: "covee-saas"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"