version: "3"
services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: "covee-saas"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    restart: "on-failure"
  smtp:
    image: "bytemark/smtp"
    ports:
      - "127.0.0.1:25:25"
    restart: "on-failure"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.0"
    ports: 
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      - discovery.type=single-node
    restart: "on-failure"
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.5.0"
    ports: 
      - "127.0.0.1:5601:5601"
    links:
      - elasticsearch
    restart: "on-failure"
  apm:
    image: "docker.elastic.co/apm/apm-server:7.5.0"
    ports: 
      - "127.0.0.1:8200:8200"
    restart: "on-failure"
  azure-blob-storage:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "127.0.0.1:10000:10000"   
    restart: "on-failure"
