version: "3.1"

services:
  postgres:
    image: postgres:alpine
    hostname: postgres-covee-saas
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: covee-saas
      POSTGRES_DB: covee-saas
