version: "3"
services:
  postgres:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_USER: "covee-saas"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
  sendgrid:
    image: "ghashange/sendgrid-mock:1.0.3"
    environment:
      API_KEY: "sendgrid-api-key"
    ports:
      - "127.0.0.1:3050:3000"
